name: Equivalent Ideas
description: The online home of Luke Bacon.
markdown: redcarpet
author: Luke Bacon
pygments: true
permalink: /:categories/:title/
timezone: Australia/Sydney
twitter: equivalentideas
url: http://equivalentideas.com
exclude: ['node_modules', 'Gruntfile.js', 'package.json', 'README.md', '*.scss']